# Generated by Django 4.2.6 on 2024-01-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='stripe_customer_id',
        ),
    ]
