# Generated by Django 4.2.6 on 2024-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='uploaded_at',
        ),
    ]
