# Generated by Django 5.0.1 on 2024-02-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_chat', '0003_pdffile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_chat.pdffile')),
            ],
        ),
    ]
