# Generated by Django 5.0.1 on 2024-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_chat', '0004_remove_pdffile_uploaded_at_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('chat_title', models.CharField(blank=True, max_length=100)),
                ('chat_history', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
