# Generated by Django 5.0.1 on 2024-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_chat', '0005_chat_delete_chathistory_delete_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
