# Generated by Django 4.2.6 on 2023-11-04 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasUsedServiceToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
