# Generated by Django 4.2.6 on 2024-01-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_hasusedservicetoday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HasUsedServiceToday',
        ),
    ]
