# Generated by Django 4.2.6 on 2024-01-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_delete_hasusedservicetoday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_started',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
    ]
